#ifndef GAMECOMMON_H
#define GAMECOMMON_H

#include "raylib.h"
#include "raymath.h"

#define TILE 4.0f 
#define MAP_SIZE 10

enum FacingDirection { FACE_N, FACE_S, FACE_E, FACE_W };

enum TileType {
    GRASS = 0, ROAD_H, ROAD_V, PROAD_V, PROAD_V1, INTERSECTION, ROUNDABOUT,
    CURVERTOP, CURVERTOP1, CURVERBOTTOM, FCURVERBOTTOM, CURVERBOTTOM1,
    TROAD, TROAD1, ROTROAD, PARKING, PARKING1, PPARKING1, PPARKING1h, PPARKING2, PPARKING2h,
    PLAYGROUND3 
};

enum FacilityType {
    NO = 0, RESTAURANT, SHOP, BCOFFEE, HOSPITAL, HOSPITAL1, HOSPITAL2, HOSPITAL3,
    PHARMACY, BUILDING_b1, FIRES, FIRES1, FIRES2, COFFE_S, BAKERY, OFFICE_C,
    MINIMARKET, POLICES, POLICES1, POLICES2, SCHOOL, SCHOOL1, SCHOOL2, GSC,
    BOOKSTORE, BUILDING_b71, BUILDING_b72, BUILDING_b8, BUILDING_b9, BOUTIQUE
};

// Ground Macros
#define G GRASS
#define H ROAD_H
#define V ROAD_V
#define PV PROAD_V
#define PV1 PROAD_V1
#define I INTERSECTION
#define R ROUNDABOUT
#define CT CURVERTOP
#define CT1 CURVERTOP1
#define CB CURVERBOTTOM
#define FCB FCURVERBOTTOM
#define CB1 CURVERBOTTOM1
#define TR TROAD
#define TR1 TROAD1
#define RTT ROTROAD
#define PP1 PPARKING1
#define PP1H PPARKING1h
#define PP2 PPARKING2
#define PP2H PPARKING2h
#define PG3 PLAYGROUND3

// Facility Macros
#define N NO
#define REST RESTAURANT
#define HP HOSPITAL
#define HP1 HOSPITAL1
#define HP2 HOSPITAL2
#define HP3 HOSPITAL3
#define PM PHARMACY
#define B1 BUILDING_b1
#define F1 FIRES
#define F2 FIRES1 
#define F3 FIRES2
#define BC BCOFFEE
#define CS COFFE_S
#define BKE BAKERY
#define OC OFFICE_C
#define MM MINIMARKET
#define PS POLICES
#define PS1 POLICES1
#define PS2 POLICES2
#define S SCHOOL
#define S1 SCHOOL1
#define S2 SCHOOL2
#define BKS BOOKSTORE
#define B71 BUILDING_b71
#define B72 BUILDING_b72
#define B8 BUILDING_b8
#define B9 BUILDING_b9
#define BQ BOUTIQUE

#endif